function vars = g_ParameterEstimation_parameters_doe(in1,in2,in3)
%G_PARAMETERESTIMATION_PARAMETERS_DOE
%    VARS = G_PARAMETERESTIMATION_PARAMETERS_DOE(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Sep-2020 17:53:33

m1 = in1(1,:);
m2 = in1(2,:);
m3 = in1(3,:);
m4 = in1(4,:);
m5 = in1(5,:);
m6 = in1(6,:);
mu1 = in2(1,:);
mu2 = in2(2,:);
mu3 = in2(3,:);
mu4 = in2(4,:);
mu5 = in2(5,:);
mu6 = in2(6,:);
rho1 = in3(1,:);
rho2 = in3(2,:);
rho3 = in3(3,:);
rho4 = in3(4,:);
rho5 = in3(5,:);
rho6 = in3(6,:);
vars = [m1;m2;m3;m4;m5;m6;mu1.*rho1;mu2.*rho2;mu3.*rho3;mu4.*rho4;mu5.*rho5;mu6.*rho6;mu1;mu2;mu3;mu4;mu5;mu6];
